version: '3'
services:
#  users_interact_api:
#    build: ./users_interact_api/src/
#    env_file:
#      - .env
#    networks:
#      - backend
#    expose:
#      - "8000"
#    volumes:
#      - /usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt:${APP_HOME}/YandexInternalRootCA.crt:rw
#    healthcheck:
#      test: [ 'CMD', 'curl', '-f', 'http://localhost:8000' ]
#      interval: 5s
#      timeout: 3s
#      retries: 5

  mongo:
    image: mongo:latest
    privileged: true
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      #- mongo-db:/data/db
      - ./mongo-local.sh:/docker-entrypoint-initdb.d/mongo-local.sh:ro
    env_file:
      - ./.env
    ports:
      - "27017:27017"

networks:
  backend:

volumes:
  mongo-db: